# Generated by Django 4.1.6 on 2023-02-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="amount",
            field=models.FloatField(default=0.0),
        ),
    ]
