# Generated by Django 4.1.6 on 2023-02-22 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expense_tracker", "0002_expense_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expensetype",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="expense_tracker.expensetype",
            ),
        ),
    ]
