# Generated by Django 4.1.6 on 2023-02-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense_tracker", "0004_expense_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="remarks",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
